--------------------------------------------------------
-- Archivo creado  - viernes-enero-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTOR
--------------------------------------------------------

  CREATE TABLE "HR"."ACTOR" 
   (	"ID_ACTOR" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"INFORMACION_INTERES" VARCHAR2(100 BYTE), 
	"ID_PELICULA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PELICULA
--------------------------------------------------------

  CREATE TABLE "HR"."PELICULA" 
   (	"ID_PELICULA" NUMBER(*,0), 
	"TITULO" VARCHAR2(50 BYTE), 
	"ANNIO" NUMBER(*,0), 
	"DIRECTOR" VARCHAR2(50 BYTE), 
	"IMPORTE" NUMBER(*,0), 
	"RECAUDACION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.ACTOR
SET DEFINE OFF;
Insert into HR.ACTOR (ID_ACTOR,NOMBRE,TIPO,INFORMACION_INTERES,ID_PELICULA) values ('1','Brad Pitt','Protagonista','Gran filmografia','1');
Insert into HR.ACTOR (ID_ACTOR,NOMBRE,TIPO,INFORMACION_INTERES,ID_PELICULA) values ('2','Roberto Benigni','Protagonista','Óscar a mejor actor','1');
Insert into HR.ACTOR (ID_ACTOR,NOMBRE,TIPO,INFORMACION_INTERES,ID_PELICULA) values ('3','Actor3','Protagonista','Óscar actor revelación','3');
Insert into HR.ACTOR (ID_ACTOR,NOMBRE,TIPO,INFORMACION_INTERES,ID_PELICULA) values ('4','Actor4','Secundario',null,'3');
REM INSERTING into HR.PELICULA
SET DEFINE OFF;
Insert into HR.PELICULA (ID_PELICULA,TITULO,ANNIO,DIRECTOR,IMPORTE,RECAUDACION) values ('1','La vida es bella','1997','Roberto Benigni','1000000','2000000');
Insert into HR.PELICULA (ID_PELICULA,TITULO,ANNIO,DIRECTOR,IMPORTE,RECAUDACION) values ('2','El club de la lucha','1999','David Fincher','2000000','3000000');
Insert into HR.PELICULA (ID_PELICULA,TITULO,ANNIO,DIRECTOR,IMPORTE,RECAUDACION) values ('3','Pelicula3','2017','Director3','1500000','4000000');
Insert into HR.PELICULA (ID_PELICULA,TITULO,ANNIO,DIRECTOR,IMPORTE,RECAUDACION) values ('4','Pelicula4','2017','Director4','300000','1000000');
--------------------------------------------------------
--  DDL for Index SYS_C007232
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007232" ON "HR"."ACTOR" ("ID_ACTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007227" ON "HR"."PELICULA" ("ID_PELICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACTOR
--------------------------------------------------------

  ALTER TABLE "HR"."ACTOR" ADD PRIMARY KEY ("ID_ACTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ACTOR" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "HR"."ACTOR" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "HR"."ACTOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ACTOR" MODIFY ("ID_ACTOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PELICULA
--------------------------------------------------------

  ALTER TABLE "HR"."PELICULA" ADD PRIMARY KEY ("ID_PELICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PELICULA" MODIFY ("RECAUDACION" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELICULA" MODIFY ("IMPORTE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELICULA" MODIFY ("DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELICULA" MODIFY ("ANNIO" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELICULA" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELICULA" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
