--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
CREATE TABLE ESTADIO(ESTADIO_ID INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, FECHA_CREACION DATE NOT NULL, NUMERO_ASIENTOS INT NOT NULL, PRIMARY KEY(ESTADIO_ID));
CREATE TABLE EQUIPO(EQUIPO_ID INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, ESTADIO_ID INT NOT NULL, PRIMARY KEY(EQUIPO_ID), CONSTRAINT EQUIPO_FK FOREIGN KEY (ESTADIO_ID) REFERENCES ESTADIO(ESTADIO_ID) ON DELETE SET NULL);
CREATE TABLE AFICION(AFICION_ID INT NOT NULL, NOMBRE_DE_GUERRA VARCHAR(50) NOT NULL, EQUIPO_ID INT NOT NULL, PRIMARY KEY(AFICION_ID), CONSTRAINT AFICION_FK FOREIGN KEY(EQUIPO_ID) REFERENCES EQUIPO(EQUIPO_ID) ON DELETE CASCADE);
CREATE TABLE CANTICO(CANTICO_ID INT NOT NULL, NOMBRE VARCHAR(200) NOT NULL, AFICION_ID INT NOT NULL, PRIMARY KEY(CANTICO_ID), CONSTRAINT CANTICO_FK FOREIGN KEY(AFICION_ID) REFERENCES AFICION(AFICION_ID) ON DELETE CASCADE);
CREATE TABLE JUGADOR(JUGADOR_ID INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, EQUIPO_ID INT, POSICION VARCHAR(50) NOT NULL, NUMERO_CAMISETA INT NOT NULL, PRIMARY KEY(JUGADOR_ID), CONSTRAINT JUGADOR_FK FOREIGN KEY(EQUIPO_ID) REFERENCES EQUIPO(EQUIPO_ID) ON DELETE SET NULL);
CREATE TABLE SEGUIDOR_PELIGROSO(SEGUIDOR_ID INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, AFICION_ID INT, FECHA_NAC DATE NOT NULL, DNI INT NOT NULL, PRIMARY KEY(SEGUIDOR_ID), CONSTRAINT SEGUIDOR_PELIGROSO_FK FOREIGN KEY(AFICION_ID) REFERENCES AFICION(AFICION_ID));

CREATE OR REPLACE FORCE VIEW "ISABEL"."SALARIOSALTOS" ("JUGADOR.NOMBRE", "EQUIPO.NOMBRE", "JUGADOR.SALARIO") AS SELECT J.NOMBRE, E.NOMBRE, SALARIO FROM JUGADOR J, EQUIPO E WHERE E.EQUIPO_ID=J.EQUIPO_ID AND SALARIO>2000 WITH READ ONLY;
